### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-js-objects-T4W3KQ#1]
@egillespie Can you take a look at this? It's [hosted here](https://levins23-kaprwtcydf6wbt4w3kq.surge.sh/) and meets the following criteria:

- [x] Your app builds on [these files](https://gist.github.com/chrisvfritz/3bd1b8d8e5b0d1ea2278ffbc561de047) (you can make changes to any of them)
- [x] When the `requestedJokeInput` has a value matching the key of an existing joke, the `jokeBox` HTML is updated [in this format](https://gist.github.com/chrisvfritz/4def3c246dfb931ecb57384a5639af99)
- [x] When the `requestedJokeInput` does _not_ match an existing joke, the `jokeBox` content is updated to `No matching joke found.`
- [x] When the `Remember this joke!` button is clicked, a new joke is saved (or overwritten) in the `jokes` object, using the data in the associated `input`/`textarea` elements
- [x] When the `Forget about it!` button is clicked, the joke with that key (if any) is deleted from the `jokes` object
- [x] Whenever the `jokes` object changes, the new version is saved in `localStorage` and used whenever the user visits the page again
- [x] It's impossible for an error to ever occur in the JavaScript console

**Comment by egillespie** [comment]
Wow, really fantastic job on this project! My only recommendation is to touch up how you create new jokes in your `jokes` object.

Right now you have this:

```js
   jokes[newJokeKey] = {}
    joke = jokes[newJokeKey]
    joke.setup = newset.value
    joke.punchline = newpunch.value
```

A shorter way to add a new joke all at once is to add the fields at the same time you create a new object, like this:

```js
   jokes[newJokeKey] = {
     setup: newset.value
     punchline: newpunch.value
   }
```

Give that a shot and let me know when you want me to take another look! 🐎

**Comment by levinsonmm** [comment]
When I try to do it the way you suggested above, I get an error that says "unexpected token punchline" on the punchline: newpunch.value line. I'm not sure why. Any ideas?

**Comment by egillespie** [comment]
Oh no! I left out a vital `,` in my example. 😭 Try this instead:

```js
   jokes[newJokeKey] = {
     setup: newset.value,
     punchline: newpunch.value
   }
```

**Comment by levinsonmm** [comment]
Alrighty, I took care of that thanks! Let me know if there's anything else.

**Comment by egillespie** [comment]
Awesome, looks great! :shipit:
